### ISSUE TITLE
support redis SCAN 

### ISSUE THREAD

**Issue by quan01994** [catcherwong/EasyCaching#12]
i want to set a list to redis ,
such as 
 key   value
 aa-0   0
 aa-1   1

**Comment by catcherwong** [comment]
@quan01994  Thanks for your interest in the project.

Do you mean you need to set multi items at once ?  

For your example ,  you want to set `<aa-0,0>` and `<aa-1,1>`  at once ?

**Comment by quan01994** [comment]
yes,but i want to get this list ,encountered a problem.
in redis ,“keys aa-*” get all keys。then mget all value 。
but keys command will block redis。

**Comment by catcherwong** [comment]
You can use command SCAN or store the keys in a set!!

And I will make some changes for this after my holiday.

**Comment by catcherwong** [comment]
@quan01994 
Version 0.14 of **EasyCaching.Redis** contains a new caching API named **GetByPrefix(Async)** that is suitable for your scenario.
