### ISSUE TITLE
i get a problem in my code

### ISSUE THREAD

**Issue by quan01994** [catcherwong/EasyCaching#16]
![image](https://user-images.githubusercontent.com/20533465/36787244-624376fa-1cc4-11e8-9dff-bbc94e3a49c6.png)

it's my code to update redis 
![image](https://user-images.githubusercontent.com/20533465/36787200-381e3540-1cc4-11e8-9f88-6833d9defe81.png)

this activity has  some property
![image](https://user-images.githubusercontent.com/20533465/36787257-739ffd10-1cc4-11e8-8aa1-042905cec294.png)

but second to insertOrUpdate  Datetime? will change value 。
I'm sure I got the value is right from foreground ,
but update reids or get from redis has some problem

**Comment by quan01994** [comment]
i think You ignore the time zone

**Comment by quan01994** [comment]
![image](https://user-images.githubusercontent.com/20533465/36788393-b546da28-1cc8-11e8-976a-764c5c32057a.png)
![image](https://user-images.githubusercontent.com/20533465/36788413-c6c0fdd8-1cc8-11e8-97b2-9dea3e96da0f.png)

**Comment by catcherwong** [comment]
@quan01994 

Hey, I add a test named [Issues16_DateTimeTest](https://github.com/catcherwong/EasyCaching/blob/dev/test/EasyCaching.UnitTests/CachingTests/RedisCachingProviderTest.cs#L25) for your case.

It runs well for me!

**Comment by quan01994** [comment]
@catcherwong 
![image](https://user-images.githubusercontent.com/20533465/36792915-e49e38f8-1cd6-11e8-9588-ce3fbfa9e79d.png)

it's my model
![image](https://user-images.githubusercontent.com/20533465/36792935-f07b8504-1cd6-11e8-96b1-dc14590dcbf6.png)

 services.AddDefaultMessagePackSerializer();

**Comment by quan01994** [comment]
you can test this.

**Comment by quan01994** [comment]
if i delete this code ,i will get this exception 
![image](https://user-images.githubusercontent.com/20533465/36793187-ab91b3fe-1cd7-11e8-89d1-d174094ec757.png)

**Comment by quan01994** [comment]
![image](https://user-images.githubusercontent.com/20533465/36793293-03c581fe-1cd8-11e8-95ff-cbfa8e298559.png)
if i delete this code .i get this exception

**Comment by quan01994** [comment]
EasyCaching.Serialization.Json  
don't find on nuget

**Comment by catcherwong** [comment]
If you want to use **MessagePackSerializer** as the default Serializer, you should not put it before the redis provider.  

**AddDefaultRedisCache** register **DefaultBinaryFormatterSerializer** as the serializer. The last one will be used!! When using  DefaultBinaryFormatterSerializer , you need to mark the class as **Serializable**

```csharp
       public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            services.AddDefaultRedisCache(option=>
            {                
                option.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6379));
                option.Password = "";                                                  
            });
            //put here!
            services.AddDefaultMessagePackSerializer();
        }
```

**Comment by catcherwong** [comment]
**EasyCaching.Serialization.Json** is not published yet!  

Maybe this weekend or next week I will publish a new version of them. It will contains the updates of #12 .

**Comment by quan01994** [comment]
i got this ,
![image](https://user-images.githubusercontent.com/20533465/36794170-91333a7a-1cda-11e8-957e-3a8be8da10d3.png)

i wan't use json FormatterSerializer

**Comment by catcherwong** [comment]
@quan01994  

I test you code, and it also return the correct result.

<img width="744" alt="screen shot 2018-02-28 at 11 11 40 pm" src="https://user-images.githubusercontent.com/8394988/36794997-d78cf59a-1cdc-11e8-96db-2ef0470a889d.png">

Here is my test code.

[EasyCachingDateTime](https://github.com/catcherwong-archive/EasyCachingDateTime)

**Comment by quan01994** [comment]
ok,thank you。

**Comment by quan01994** [comment]
I used the wrong method when I used it 。so i get some Inexplicable mistake。
Very much looking forward to new features
