### ISSUE TITLE
感谢提供AspectCore的支持

### ISSUE THREAD

**Issue by liuhaoyang** [catcherwong/EasyCaching#5]
我是AspectCore作者，感谢EasyCaching提供对AspectCore的支持，并且已经把EasyCaching加入到AspectCore的[组件列表](https://github.com/dotnetcore/AspectCore-Framework/blob/master/README.md#who-is-using)中

**Comment by catcherwong** [comment]
因为AspectCore确实很好用，所以才考虑把它用起来！:smile:

谢谢 @liuhaoyang  提供一个这么:thumbsup:的库！
